# Birthday Plugin Configuration

# 数据存储配置
# 支持两种模式：
# FILE - 使用本地YAML文件存储（默认，单服模式）
# DATABASE - 使用MySQL数据库存储（推荐，支持跨服）
storage:
  type: FILE
  
# 数据库配置 (当 storage.type 为 DATABASE 时使用)
# 多个服务器可以连接到同一个数据库实现数据共享
database:
  host: "localhost"          # 数据库主机地址
  port: 3306                 # 数据库端口
  database: "minecraft"      # 数据库名称
  username: "root"           # 数据库用户名
  password: ""               # 数据库密码
  useSSL: false             # 是否使用SSL连接
  table-prefix: "birthday_"  # 表前缀，多个插件实例可使用不同前缀
  max-connections: 10        # 连接池最大连接数
  connection-timeout: 5000   # 连接超时时间(毫秒)

# 消息配置
messages:
  prefix: "&b&l『ICT』>> &r"
  birthday-set: "&a生日信息设置成功！你的生日是 %month%月%day%日"
  birthday-broadcast: "&6&l今天是 %player% 的生日！"
  birthday-title: "&6&l生日快乐！"
  birthday-subtitle: "&e祝你生日快乐！"
  wish-success: "感谢你向 %player% 送上生日祝福！"
  wish-already: "你今天已经送过生日祝福了！"
  no-birthday-today: "&c今天没有人过生日哦！"
  error-save: "&c保存生日信息时发生错误，请联系管理员！"
  command-player-only: "&c此命令只能由玩家使用！"
  birthday-not-set: "&e你还没有设置生日信息！"
  birthday-info: "&a你的生日是: %month%月%day%日"
  birthday-reminder: "&e再过%days%天就是你的生日了！"

# 烟花效果配置
firework:
  enabled: true
  count: 5
  power: 2
  colors:
    - RED
    - YELLOW
    - BLUE
  fade-colors:
    - PINK
  trail: true
  flicker: true
  launch-interval: 10 # ticks

# GUI配置
gui:
  month:
    title: "请选择生日月份"
    size: 27
    background: BLACK_STAINED_GLASS_PANE
    item:
      material: PAPER
      name: "&6%month%月"
      lore:
        - "&7点击选择"
  day:
    title: "请选择生日日期"
    size: 36
    background: LIGHT_BLUE_STAINED_GLASS_PANE
    item:
      material: PAPER
      name: "&b%day%日"

# 系统设置
settings:
  save-interval: 6000 # ticks (5分钟)
  first-join-gui: true

# 特效配置
effects:
  duration: 100 # 持续5秒
  sound:
    enabled: true
    sounds:
      - sound: ENTITY_PLAYER_LEVELUP
        pitch: 1.0
        volume: 1.0
      - sound: ENTITY_FIREWORK_ROCKET_LAUNCH
        pitch: 0.5
        volume: 2.0
  particle:
    enabled: true
    interval: 2 # ticks
    count: 1
    types:
      - HEART
      - TOTEM
      - NOTE
    radius: 1.5
    height-variation: 0.5 